-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE todos (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 description TEXT,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_todos_status ON todos(status);
CREATE INDEX idx_todos_created_at ON todos(created_at DESC);

