-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE goals (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 description TEXT,
 type TEXT NOT NULL,
 target_date DATE,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_goals_type ON goals(type);
CREATE INDEX idx_goals_status ON goals(status);
CREATE INDEX idx_goals_target_date ON goals(target_date);

