-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE investment_reviews (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 date DATE NOT NULL,
 content TEXT NOT NULL,
 market_summary TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_investment_reviews_date ON investment_reviews(date DESC);

