-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE hot_news (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 content TEXT NOT NULL,
 source TEXT,
 url TEXT,
 published_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_hot_news_published_at ON hot_news(published_at DESC);

