-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE investment_knowledge (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 content TEXT NOT NULL,
 category TEXT,
 tags TEXT[],
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_investment_knowledge_category ON investment_knowledge(category);
CREATE INDEX idx_investment_knowledge_created_at ON investment_knowledge(created_at DESC);

