-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE career_timeline (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 company TEXT NOT NULL,
 position TEXT NOT NULL,
 start_date DATE NOT NULL,
 end_date DATE,
 projects TEXT[],
 responsibilities TEXT,
 salary TEXT,
 is_current BOOLEAN DEFAULT false,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_career_timeline_start_date ON career_timeline(start_date DESC);

